name: rememberme
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_bloc: ^8.1.3
  bloc: ^8.1.2
  equatable: ^2.0.5
  image_picker: ^1.0.4
  package_info_plus: ^5.0.1
  url_launcher: ^6.2.1
  uuid: ^4.2.1

  # Firebase (später aktivieren)
  # firebase_core: ^2.15.0
  # firebase_auth: ^4.7.0
  # cloud_firestore: ^4.8.0
  # firebase_storage: ^11.2.0

  # UI & Design
  cupertino_icons: ^1.0.6

  # QR Code Scanner (später hinzufügen)
  # mobile_scanner: ^3.5.0
  # qr_flutter: ^4.1.0

  # Image Handling
  # image_picker: ^1.0.0
  # cached_network_image: ^3.2.3

  # Utilities
  # intl: ^0.18.0
  # path_provider: ^2.1.0
  # shared_preferences: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # Hier können später Assets hinzugefügt werden:
  # assets:
  #   - assets/images/
  #   - assets/icons/

  # Fonts können hier hinzugefügt werden:
  # fonts:
  #   - family: CustomFont
  #     fonts:
  #       - asset: fonts/CustomFont-Regular.ttf
  #       - asset: fonts/CustomFont-Bold.ttf
  #         weight: 700
